#!/usr/local/bin/bash
#
VlogDef1="+define+CHERIoT"
VlogDef2="+define+KUDU_PPL_CFG=1"
VlogDef3="+define+TraceDPI"
VlogDef4=""
VlogDef5=""
VlogDef6=""
FileList="kudu.verilator.f"
RunDII="false"

# Loop over args
for arg in "$@"; do
  case "$arg" in
    -rv32)  
      VlogDef1="" 
      ;;
    -conf0) VlogDef2="+define+KUDU_PPL_CFG=0" ;;
    -conf1) VlogDef2="+define+KUDU_PPL_CFG=1" ;;
    -conf2) VlogDef2="+define+KUDU_PPL_CFG=2" ;;
    -conf3) VlogDef2="+define+KUDU_PPL_CFG=3" ;;
    -dw)
      VlogDef3="+define+KUDU_DW_MULT=1"
      FileList="kudu_dw.vcs.f" 
      ;;
    -riscv_test) VlogDef4="+define+RISCV_TEST_SUITE" ;;
    -dii)
      #VlogDef5="+define+DII_SIM -LDFLAGS \"-L. -lsparse_mem\""
      VlogDef5="+define+DII_SIM"
      RunDII="true"
      ;;
    *)
      echo "Warning: Unknown option $arg" >&2
      ;;
  esac
done

VlogDefs="$VlogDef1 $VlogDef2 $VlogDef3 $VlogDef4 $VlogDef5 $VlogDef6 +define+NO_FSDB"
echo "VlogDefs=$VlogDefs  FileList=$FileList"


export rtlRoot=../../rtl
export verifRoot=..
export dwRoot=../../dw


verilator -cc --timing  --unroll-count 128 --top-module tb_kudu_top -exe $MainFile $DpiFile $VlogDefs  -f $FileList

# vcs -full64 -sverilog -xlrm uniq_prior_final +systemverilogext+sv +lint=TFIPC-L -timescale=1ns/1ps -debug_acc+all -o $OutFile $VlogDefs -f $FileList
