
// Generated first-pass DPI-C port of tracer_pkg.sv.
// Top-level DPI symbol: decode_rvfi_instr
//
// Notes:
//   * This is simulation-only code intended for Verilator DPI-C.
//   * OPCODE_CHERI and OPCODE_AUICGP are supplied as defaults below. If your
//     super_pkg uses different values, compile with -DTRACER_OPCODE_CHERI=...
//     and/or -DTRACER_OPCODE_AUICGP=...
//   * The SV wrapper in tracer_dpi_wrapper.sv flattens rvfi_t into this DPI call.

#include <cstdint>
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <sstream>
#include <iomanip>
#include <string>

// generated by AI but not actually used..
#ifndef TRACER_OPCODE_CHERI
#define TRACER_OPCODE_CHERI 0x5b
#endif

#ifndef TRACER_OPCODE_AUICGP
#define TRACER_OPCODE_AUICGP 0x0b
#endif

namespace tracer_dpi {

struct Pattern {
  uint32_t value;
  uint32_t mask;
  int width;
};

static inline bool match(uint32_t insn, Pattern p) {
  uint32_t mask = p.width == 16 ? (p.mask & 0xffffu) : p.mask;
  uint32_t value = p.width == 16 ? (p.value & 0xffffu) : p.value;
  return (insn & mask) == value;
}

static constexpr Pattern INSN_ADD = {0x33u, 0xfe00707fu, 32};
static constexpr Pattern INSN_ADDI = {0x13u, 0x707fu, 32};
static constexpr Pattern INSN_AMOADD = {0x202fu, 0x7800707fu, 32};
static constexpr Pattern INSN_AMOAND = {0x6000202fu, 0x7800707fu, 32};
static constexpr Pattern INSN_AMOMAX = {0xa000202fu, 0xf800707fu, 32};
static constexpr Pattern INSN_AMOMAXU = {0xe000202fu, 0xf800707fu, 32};
static constexpr Pattern INSN_AMOMIN = {0x8000202fu, 0xf800707fu, 32};
static constexpr Pattern INSN_AMOMINU = {0xc000202fu, 0xf800707fu, 32};
static constexpr Pattern INSN_AMOOR = {0x4000202fu, 0x7800707fu, 32};
static constexpr Pattern INSN_AMOSWAP = {0x800202fu, 0x7800707fu, 32};
static constexpr Pattern INSN_AMOXOR = {0x2000202fu, 0x7800707fu, 32};
static constexpr Pattern INSN_AND = {0x7033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_ANDI = {0x7013u, 0x707fu, 32};
static constexpr Pattern INSN_ANDN = {0x40007033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_AUICGP = {0x7bu, 0x7fu, 32};
static constexpr Pattern INSN_AUIPC = {0x17u, 0x7fu, 32};
static constexpr Pattern INSN_BCLR = {0x48001033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_BCLRI = {0x48001013u, 0xf800707fu, 32};
static constexpr Pattern INSN_BCOMPRESS = {0x8006033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_BDECOMPRESS = {0x48006033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_BEQ = {0x63u, 0x707fu, 32};
static constexpr Pattern INSN_BEXT = {0x48005033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_BEXTI = {0x48005013u, 0xfc00707fu, 32};
static constexpr Pattern INSN_BFP = {0x48007033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_BGE = {0x5063u, 0x707fu, 32};
static constexpr Pattern INSN_BGEU = {0x7063u, 0x707fu, 32};
static constexpr Pattern INSN_BINV = {0x68001033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_BINVI = {0x68001013u, 0xf800707fu, 32};
static constexpr Pattern INSN_BLT = {0x4063u, 0x707fu, 32};
static constexpr Pattern INSN_BLTU = {0x6063u, 0x707fu, 32};
static constexpr Pattern INSN_BNE = {0x1063u, 0x707fu, 32};
static constexpr Pattern INSN_BSET = {0x28001033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_BSETI = {0x28001013u, 0xf800707fu, 32};
static constexpr Pattern INSN_CADD = {0x9002u, 0xf003u, 16};
static constexpr Pattern INSN_CADDI = {0x1u, 0xe003u, 16};
static constexpr Pattern INSN_CADDI4SPN = {0x0u, 0xe003u, 16};
static constexpr Pattern INSN_CAND = {0x8c61u, 0xfc63u, 16};
static constexpr Pattern INSN_CANDI = {0x8801u, 0xec03u, 16};
static constexpr Pattern INSN_CBEQZ = {0xc001u, 0xe003u, 16};
static constexpr Pattern INSN_CBNEZ = {0xe001u, 0xe003u, 16};
static constexpr Pattern INSN_CCLC = {0x6000u, 0xe003u, 16};
static constexpr Pattern INSN_CCLCSP = {0x6002u, 0xe003u, 16};
static constexpr Pattern INSN_CCSC = {0xe000u, 0xe003u, 16};
static constexpr Pattern INSN_CCSCSP = {0xe002u, 0xe003u, 16};
static constexpr Pattern INSN_CEBREAK = {0x9002u, 0xf7bfu, 16};
static constexpr Pattern INSN_CHANDPERM = {0x1a00005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHCLEARTAG = {0xfeb0005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHCRAM = {0xfe90005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHCRRL = {0xfe80005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHCSRRW = {0x200005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHGETADDR = {0xfef0005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHGETBASE = {0xfe20005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHGETHIGH = {0xff70005bu, 0xfff0707fu, 32};
static constexpr Pattern INSN_CHGETLEN = {0xfe30005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHGETPERM = {0xfe00005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHGETSEALED = {0xfe50005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHGETTAG = {0xfe40005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHGETTOP = {0xff80005bu, 0xfff0707fu, 32};
static constexpr Pattern INSN_CHGETTYPE = {0xfe10005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHINCADDR = {0x2200005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHINCADDRIMM = {0x105bu, 0x707fu, 32};
static constexpr Pattern INSN_CHJALR = {0xfec0005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHMOVE = {0xfea0005bu, 0xfef0707fu, 32};
static constexpr Pattern INSN_CHSEAL = {0x1600005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHSETADDR = {0x2000005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHSETBOUNDS = {0x1000005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHSETBOUNDSEX = {0x1200005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHSETBOUNDSIMM = {0x205bu, 0x707fu, 32};
static constexpr Pattern INSN_CHSETBOUNDSRNDN = {0x1400005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHSETEQUAL = {0x4200005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHSETHIGH = {0x2c00005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHSUB = {0x2800005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHTESTSUB = {0x4000005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CHUNSEAL = {0x1800005bu, 0xfe00707fu, 32};
static constexpr Pattern INSN_CJ = {0xa001u, 0xe003u, 16};
static constexpr Pattern INSN_CJAL = {0x2001u, 0xe003u, 16};
static constexpr Pattern INSN_CJALR = {0x9002u, 0xf03fu, 16};
static constexpr Pattern INSN_CJR = {0x8002u, 0xf7bfu, 16};
static constexpr Pattern INSN_CLI = {0x4001u, 0xe003u, 16};
static constexpr Pattern INSN_CLMUL = {0xa001033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_CLMULH = {0xa003033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_CLMULR = {0xa002033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_CLUI = {0x6001u, 0xe003u, 16};
static constexpr Pattern INSN_CLW = {0x4000u, 0xe003u, 16};
static constexpr Pattern INSN_CLWSP = {0x4002u, 0xe003u, 16};
static constexpr Pattern INSN_CLZ = {0x60001013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_CMIX = {0x6001033u, 0x600707fu, 32};
static constexpr Pattern INSN_CMOV = {0x6005033u, 0x600707fu, 32};
static constexpr Pattern INSN_CMV = {0x8002u, 0xf003u, 16};
static constexpr Pattern INSN_COR = {0x8c41u, 0xfc63u, 16};
static constexpr Pattern INSN_CPOP = {0x60201013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_CRC32C_B = {0x61801013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_CRC32C_H = {0x61901013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_CRC32C_W = {0x61a01013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_CRC32_B = {0x61001013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_CRC32_H = {0x61101013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_CRC32_W = {0x61201013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_CSLLI = {0x2u, 0xe003u, 16};
static constexpr Pattern INSN_CSRAI = {0x8401u, 0xec03u, 16};
static constexpr Pattern INSN_CSRLI = {0x8001u, 0xec03u, 16};
static constexpr Pattern INSN_CSRRC = {0x3073u, 0x707fu, 32};
static constexpr Pattern INSN_CSRRCI = {0x7073u, 0x707fu, 32};
static constexpr Pattern INSN_CSRRS = {0x2073u, 0x707fu, 32};
static constexpr Pattern INSN_CSRRSI = {0x6073u, 0x707fu, 32};
static constexpr Pattern INSN_CSRRW = {0x1073u, 0x707fu, 32};
static constexpr Pattern INSN_CSRRWI = {0x5073u, 0x707fu, 32};
static constexpr Pattern INSN_CSUB = {0x8c01u, 0xfc63u, 16};
static constexpr Pattern INSN_CSW = {0xc000u, 0xe003u, 16};
static constexpr Pattern INSN_CTZ = {0x60101013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_CXOR = {0x8c21u, 0xfc63u, 16};
static constexpr Pattern INSN_DIV = {0x2004033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_DIVU = {0x2005033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_DRET = {0x7b200073u, 0xfff000ffu, 32};
static constexpr Pattern INSN_EBREAK = {0x100073u, 0xfff000ffu, 32};
static constexpr Pattern INSN_ECALL = {0x73u, 0xfff000ffu, 32};
static constexpr Pattern INSN_FENCE = {0xfu, 0x707fu, 32};
static constexpr Pattern INSN_FENCEI = {0x100fu, 0x7f7ffu, 32};
static constexpr Pattern INSN_FSL = {0x4001033u, 0x600707fu, 32};
static constexpr Pattern INSN_FSR = {0x4005033u, 0x600707fu, 32};
static constexpr Pattern INSN_FSRI = {0x4005013u, 0x400707fu, 32};
static constexpr Pattern INSN_GORC = {0x28005033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_GORCI = {0x28005013u, 0xfc00707fu, 32};
static constexpr Pattern INSN_GREV = {0x68005033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_GREVI = {0x68005013u, 0xfc00707fu, 32};
static constexpr Pattern INSN_JAL = {0x6fu, 0x7fu, 32};
static constexpr Pattern INSN_JALR = {0x67u, 0x707fu, 32};
static constexpr Pattern INSN_LOAD = {0x3u, 0x7fu, 32};
static constexpr Pattern INSN_LR = {0x1000202fu, 0x78f0707fu, 32};
static constexpr Pattern INSN_LUI = {0x37u, 0x7fu, 32};
static constexpr Pattern INSN_MAX = {0xa006033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_MAXU = {0xa007033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_MIN = {0xa004033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_MINU = {0xa005033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_MRET = {0x30200073u, 0xfff000ffu, 32};
static constexpr Pattern INSN_OR = {0x6033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_ORC = {0x29f05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC16 = {0x29005013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC2 = {0x29e05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC2_B = {0x28605013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC2_H = {0x28e05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC2_N = {0x28205013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC4 = {0x29c05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC4_B = {0x28405013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC4_H = {0x28c05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC8 = {0x29805013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC8_H = {0x28805013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC_B = {0x28705013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC_H = {0x28f05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC_N = {0x28305013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORC_P = {0x28105013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ORI = {0x6013u, 0x707fu, 32};
static constexpr Pattern INSN_ORN = {0x40006033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_PACK = {0x8004033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_PACKH = {0x8007033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_PACKU = {0x48004033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_PMUH = {0x2001033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_PMUL = {0x2000033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_PMULHSU = {0x2002033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_PMULHU = {0x2003033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_REM = {0x2006033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_REMU = {0x2007033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_REV = {0x69f05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV16 = {0x69005013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV2 = {0x69e05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV2_B = {0x68605013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV2_H = {0x68e05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV2_N = {0x68205013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV4 = {0x69c05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV4_B = {0x68405013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV4_H = {0x68c05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV8 = {0x69805013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV8_H = {0x68805013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV_B = {0x68705013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV_H = {0x68f05013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV_N = {0x68305013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_REV_P = {0x68105013u, 0xfdf0707fu, 32};
static constexpr Pattern INSN_ROL = {0x60001033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_ROR = {0x60005033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_RORI = {0x60005013u, 0xfc00707fu, 32};
static constexpr Pattern INSN_SC = {0x1800202fu, 0x7800707fu, 32};
static constexpr Pattern INSN_SEXTB = {0x60401013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_SEXTH = {0x60501013u, 0xfff0707fu, 32};
static constexpr Pattern INSN_SH1ADD = {0x20002033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SH2ADD = {0x20004033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SH3ADD = {0x20006033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SHFL = {0x8001033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SHFLI = {0x8001013u, 0xfc00707fu, 32};
static constexpr Pattern INSN_SLL = {0x1033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SLLI = {0x1013u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SLO = {0x20001033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SLOI = {0x20001013u, 0xf800707fu, 32};
static constexpr Pattern INSN_SLT = {0x2033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SLTI = {0x2013u, 0x707fu, 32};
static constexpr Pattern INSN_SLTIU = {0x3013u, 0x707fu, 32};
static constexpr Pattern INSN_SLTU = {0x3033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SRA = {0x40005033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SRAI = {0x40005013u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SRL = {0x5033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SRLI = {0x5013u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SRO = {0x20005033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SROI = {0x20005013u, 0xfc00707fu, 32};
static constexpr Pattern INSN_STORE = {0x23u, 0x7fu, 32};
static constexpr Pattern INSN_SUB = {0x40000033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_SWSP = {0xc002u, 0xe003u, 16};
static constexpr Pattern INSN_UNSHFL = {0x8005033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_UNSHFLI = {0x8005013u, 0xfc00707fu, 32};
static constexpr Pattern INSN_UNZIP = {0x8f05013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_UNZIP2 = {0x8e05013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_UNZIP2_B = {0x8205013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_UNZIP2_H = {0x8605013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_UNZIP4 = {0x8c05013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_UNZIP4_H = {0x8405013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_UNZIP8 = {0x8805013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_UNZIP_B = {0x8305013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_UNZIP_H = {0x8705013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_UNZIP_N = {0x8105013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_WFI = {0x10500073u, 0xfff000ffu, 32};
static constexpr Pattern INSN_XNOR = {0x40004033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_XOR = {0x4033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_XORI = {0x4013u, 0x707fu, 32};
static constexpr Pattern INSN_XPERM_B = {0x28004033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_XPERM_H = {0x28006033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_XPERM_N = {0x28002033u, 0xfe00707fu, 32};
static constexpr Pattern INSN_ZEXTH = {0x8004033u, 0xfff0707fu, 32};
static constexpr Pattern INSN_ZIP = {0x8f01013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_ZIP2 = {0x8e01013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_ZIP2_B = {0x8201013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_ZIP2_H = {0x8601013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_ZIP4 = {0x8c01013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_ZIP4_H = {0x8401013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_ZIP8 = {0x8801013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_ZIP_B = {0x8301013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_ZIP_H = {0x8701013u, 0xfcf0707fu, 32};
static constexpr Pattern INSN_ZIP_N = {0x8101013u, 0xfcf0707fu, 32};

enum DataAccess : uint16_t {
  RS1  = 1u << 0,
  RS2  = 1u << 1,
  RS3  = 1u << 2,
  RD   = 1u << 3,
  MEM  = 1u << 4,
  CS1  = 1u << 5,
  CS2  = 1u << 6,
  CD   = 1u << 7,
  MEMC = 1u << 8,
  MEM2 = 1u << 9,
};

struct RvfiData {
  uint32_t insn;
  bool trap;
  bool intr;
  uint8_t rs1_addr;
  uint8_t rs2_addr;
  uint8_t rs3_addr;
  uint32_t rs1_rdata_lo;
  uint32_t rs2_rdata_lo;
  uint32_t rs3_rdata_lo;
  uint64_t rs1_rdata_hi;
  uint64_t rs2_rdata_hi;
  uint64_t rs3_rdata_hi;
  uint8_t rd_addr;
  uint32_t rd_wdata_lo;
  uint64_t rd_wdata_hi;
  uint32_t pc_rdata;
  uint32_t pc_wdata;
  uint32_t mem_addr;
  uint8_t mem_rmask;
  uint8_t mem_wmask;
  uint32_t mem_rdata_lo;
  uint32_t mem_wdata_lo;
  uint64_t mem_rdata_hi;
  uint64_t mem_wdata_hi;
  bool cheri_pmode;
};

static std::string fmt(const char* format, ...) {
  char local[512];

  va_list args;
  va_start(args, format);
  int n = vsnprintf(local, sizeof(local), format, args);
  va_end(args);

  if (n < 0) {
    return "";
  }

  if ((size_t)n < sizeof(local)) {
    return std::string(local, (size_t)n);
  }

  std::string out((size_t)n + 1, '\0');

  va_start(args, format);
  int n2 = vsnprintf(&out[0], out.size(), format, args);
  va_end(args);

  if (n2 < 0) {
    return "";
  }

  out.resize((size_t)n);
  return out;
}


static inline uint32_t bits(uint32_t v, int hi, int lo) {
  return (v >> lo) & ((uint32_t{1} << (hi - lo + 1)) - 1u);
}

static inline int32_t sext(uint32_t v, int width) {
  uint32_t m = 1u << (width - 1);
  return static_cast<int32_t>((v ^ m) - m);
}

static inline uint32_t reg_lo32(uint64_t v) { return static_cast<uint32_t>(v); }

static std::string reg_addr_to_str(uint32_t addr) {
  return addr < 10 ? fmt(" x%u", addr) : fmt("x%u", addr);
}

static std::string get_scr_name(uint32_t scr_addr) {
  switch (scr_addr) {
    case 27: return "ztopc";
    case 28: return "mtcc";
    case 29: return "mtdc";
    case 30: return "mscratchc";
    case 31: return "mepcc";
    default: return fmt("scr%u", scr_addr);
  }
}

static std::string get_csr_name(uint32_t csr_addr) {
  switch (csr_addr) {
    case 0: return "ustatus";
    case 4: return "uie";
    case 5: return "utvec";
    case 64: return "uscratch";
    case 65: return "uepc";
    case 66: return "ucause";
    case 67: return "utval";
    case 68: return "uip";
    case 1: return "fflags";
    case 2: return "frm";
    case 3: return "fcsr";
    case 3072: return "cycle";
    case 3073: return "time";
    case 3074: return "instret";
    case 3075: return "hpmcounter3";
    case 3076: return "hpmcounter4";
    case 3077: return "hpmcounter5";
    case 3078: return "hpmcounter6";
    case 3079: return "hpmcounter7";
    case 3080: return "hpmcounter8";
    case 3081: return "hpmcounter9";
    case 3082: return "hpmcounter10";
    case 3083: return "hpmcounter11";
    case 3084: return "hpmcounter12";
    case 3085: return "hpmcounter13";
    case 3086: return "hpmcounter14";
    case 3087: return "hpmcounter15";
    case 3088: return "hpmcounter16";
    case 3089: return "hpmcounter17";
    case 3090: return "hpmcounter18";
    case 3091: return "hpmcounter19";
    case 3092: return "hpmcounter20";
    case 3093: return "hpmcounter21";
    case 3094: return "hpmcounter22";
    case 3095: return "hpmcounter23";
    case 3096: return "hpmcounter24";
    case 3097: return "hpmcounter25";
    case 3098: return "hpmcounter26";
    case 3099: return "hpmcounter27";
    case 3100: return "hpmcounter28";
    case 3101: return "hpmcounter29";
    case 3102: return "hpmcounter30";
    case 3103: return "hpmcounter31";
    case 3200: return "cycleh";
    case 3201: return "timeh";
    case 3202: return "instreth";
    case 3203: return "hpmcounter3h";
    case 3204: return "hpmcounter4h";
    case 3205: return "hpmcounter5h";
    case 3206: return "hpmcounter6h";
    case 3207: return "hpmcounter7h";
    case 3208: return "hpmcounter8h";
    case 3209: return "hpmcounter9h";
    case 3210: return "hpmcounter10h";
    case 3211: return "hpmcounter11h";
    case 3212: return "hpmcounter12h";
    case 3213: return "hpmcounter13h";
    case 3214: return "hpmcounter14h";
    case 3215: return "hpmcounter15h";
    case 3216: return "hpmcounter16h";
    case 3217: return "hpmcounter17h";
    case 3218: return "hpmcounter18h";
    case 3219: return "hpmcounter19h";
    case 3220: return "hpmcounter20h";
    case 3221: return "hpmcounter21h";
    case 3222: return "hpmcounter22h";
    case 3223: return "hpmcounter23h";
    case 3224: return "hpmcounter24h";
    case 3225: return "hpmcounter25h";
    case 3226: return "hpmcounter26h";
    case 3227: return "hpmcounter27h";
    case 3228: return "hpmcounter28h";
    case 3229: return "hpmcounter29h";
    case 3230: return "hpmcounter30h";
    case 3231: return "hpmcounter31h";
    case 256: return "sstatus";
    case 258: return "sedeleg";
    case 259: return "sideleg";
    case 260: return "sie";
    case 261: return "stvec";
    case 262: return "scounteren";
    case 320: return "sscratch";
    case 321: return "sepc";
    case 322: return "scause";
    case 323: return "stval";
    case 324: return "sip";
    case 384: return "satp";
    case 3857: return "mvendorid";
    case 3858: return "marchid";
    case 3859: return "mimpid";
    case 3860: return "mhartid";
    case 768: return "mstatus";
    case 769: return "misa";
    case 770: return "medeleg";
    case 771: return "mideleg";
    case 772: return "mie";
    case 773: return "mtvec";
    case 774: return "mcounteren";
    case 832: return "mscratch";
    case 833: return "mepc";
    case 834: return "mcause";
    case 835: return "mtval";
    case 836: return "mip";
    case 928: return "pmpcfg0";
    case 929: return "pmpcfg1";
    case 930: return "pmpcfg2";
    case 931: return "pmpcfg3";
    case 944: return "pmpaddr0";
    case 945: return "pmpaddr1";
    case 946: return "pmpaddr2";
    case 947: return "pmpaddr3";
    case 948: return "pmpaddr4";
    case 949: return "pmpaddr5";
    case 950: return "pmpaddr6";
    case 951: return "pmpaddr7";
    case 952: return "pmpaddr8";
    case 953: return "pmpaddr9";
    case 954: return "pmpaddr10";
    case 955: return "pmpaddr11";
    case 956: return "pmpaddr12";
    case 957: return "pmpaddr13";
    case 958: return "pmpaddr14";
    case 959: return "pmpaddr15";
    case 2816: return "mcycle";
    case 2818: return "minstret";
    case 2819: return "mhpmcounter3";
    case 2820: return "mhpmcounter4";
    case 2821: return "mhpmcounter5";
    case 2822: return "mhpmcounter6";
    case 2823: return "mhpmcounter7";
    case 2824: return "mhpmcounter8";
    case 2825: return "mhpmcounter9";
    case 2826: return "mhpmcounter10";
    case 2827: return "mhpmcounter11";
    case 2828: return "mhpmcounter12";
    case 2829: return "mhpmcounter13";
    case 2830: return "mhpmcounter14";
    case 2831: return "mhpmcounter15";
    case 2832: return "mhpmcounter16";
    case 2833: return "mhpmcounter17";
    case 2834: return "mhpmcounter18";
    case 2835: return "mhpmcounter19";
    case 2836: return "mhpmcounter20";
    case 2837: return "mhpmcounter21";
    case 2838: return "mhpmcounter22";
    case 2839: return "mhpmcounter23";
    case 2840: return "mhpmcounter24";
    case 2841: return "mhpmcounter25";
    case 2842: return "mhpmcounter26";
    case 2843: return "mhpmcounter27";
    case 2844: return "mhpmcounter28";
    case 2845: return "mhpmcounter29";
    case 2846: return "mhpmcounter30";
    case 2847: return "mhpmcounter31";
    case 2944: return "mcycleh";
    case 2946: return "minstreth";
    case 2947: return "mhpmcounter3h";
    case 2948: return "mhpmcounter4h";
    case 2949: return "mhpmcounter5h";
    case 2950: return "mhpmcounter6h";
    case 2951: return "mhpmcounter7h";
    case 2952: return "mhpmcounter8h";
    case 2953: return "mhpmcounter9h";
    case 2954: return "mhpmcounter10h";
    case 2955: return "mhpmcounter11h";
    case 2956: return "mhpmcounter12h";
    case 2957: return "mhpmcounter13h";
    case 2958: return "mhpmcounter14h";
    case 2959: return "mhpmcounter15h";
    case 2960: return "mhpmcounter16h";
    case 2961: return "mhpmcounter17h";
    case 2962: return "mhpmcounter18h";
    case 2963: return "mhpmcounter19h";
    case 2964: return "mhpmcounter20h";
    case 2965: return "mhpmcounter21h";
    case 2966: return "mhpmcounter22h";
    case 2967: return "mhpmcounter23h";
    case 2968: return "mhpmcounter24h";
    case 2969: return "mhpmcounter25h";
    case 2970: return "mhpmcounter26h";
    case 2971: return "mhpmcounter27h";
    case 2972: return "mhpmcounter28h";
    case 2973: return "mhpmcounter29h";
    case 2974: return "mhpmcounter30h";
    case 2975: return "mhpmcounter31h";
    case 803: return "mhpmevent3";
    case 804: return "mhpmevent4";
    case 805: return "mhpmevent5";
    case 806: return "mhpmevent6";
    case 807: return "mhpmevent7";
    case 808: return "mhpmevent8";
    case 809: return "mhpmevent9";
    case 810: return "mhpmevent10";
    case 811: return "mhpmevent11";
    case 812: return "mhpmevent12";
    case 813: return "mhpmevent13";
    case 814: return "mhpmevent14";
    case 815: return "mhpmevent15";
    case 816: return "mhpmevent16";
    case 817: return "mhpmevent17";
    case 818: return "mhpmevent18";
    case 819: return "mhpmevent19";
    case 820: return "mhpmevent20";
    case 821: return "mhpmevent21";
    case 822: return "mhpmevent22";
    case 823: return "mhpmevent23";
    case 824: return "mhpmevent24";
    case 825: return "mhpmevent25";
    case 826: return "mhpmevent26";
    case 827: return "mhpmevent27";
    case 828: return "mhpmevent28";
    case 829: return "mhpmevent29";
    case 830: return "mhpmevent30";
    case 831: return "mhpmevent31";
    case 1952: return "tselect";
    case 1953: return "tdata1";
    case 1954: return "tdata2";
    case 1955: return "tdata3";
    case 1968: return "dcsr";
    case 1969: return "dpc";
    case 1970: return "dscratch";
    case 512: return "hstatus";
    case 514: return "hedeleg";
    case 515: return "hideleg";
    case 516: return "hie";
    case 517: return "htvec";
    case 576: return "hscratch";
    case 577: return "hepc";
    case 578: return "hcause";
    case 579: return "hbadaddr";
    case 580: return "hip";
    case 896: return "mbase";
    case 897: return "mbound";
    case 898: return "mibase";
    case 899: return "mibound";
    case 900: return "mdbase";
    case 901: return "mdbound";
    case 800: return "mcountinhibit";
    case 3009: return "mshwm";
    case 3010: return "mshwmb";
    case 3012: return "cdbgctrl";
    default: return fmt("0x%x", csr_addr);
  }
}

static std::string build_disp_str(const std::string& decode_str, const RvfiData& d,
                                  uint16_t data_accessed) {
  std::ostringstream oss;
  //  oss << std::hex << std::nouppercase << d.pc_rdata << "\t";
  oss << std::hex  << std::nouppercase  << std::setw(8) << std::setfill('0') << d.pc_rdata << "\t";

  if ((d.insn & 0x3u) != 0x3u) {
    oss << "    " << std::setw(4) << std::setfill('0') << (d.insn & 0xffffu);
  } else {
    oss << std::setw(8) << std::setfill('0') << d.insn;
  }
  oss << "\t";

  if (d.trap) oss << "-->";
  oss << decode_str << "\t";

  auto add_reg_read = [&](uint8_t addr, uint32_t lo) {
    oss << " " << reg_addr_to_str(addr) << ":0x"
        << std::setw(8) << std::setfill('0') << lo;
  };
  auto add_cap_read = [&](uint8_t addr, uint32_t lo, uint64_t hi) {
    oss << " " << reg_addr_to_str(addr) << ":0x"
        << std::setw(8) << std::setfill('0') << lo
        << "+0x" << std::setw(9) << std::setfill('0') << hi;
  };
  auto add_reg_write = [&](uint8_t addr, uint32_t lo) {
    oss << " " << reg_addr_to_str(addr) << "=0x"
        << std::setw(8) << std::setfill('0') << lo;
  };
  auto add_cap_write = [&](uint8_t addr, uint32_t lo, uint64_t hi) {
    oss << " " << reg_addr_to_str(addr) << "=0x"
        << std::setw(8) << std::setfill('0') << lo
        << "+0x" << std::setw(9) << std::setfill('0') << hi;
  };


  if (data_accessed & RS1) add_reg_read(d.rs1_addr, reg_lo32(d.rs1_rdata_lo));
  if (data_accessed & CS1) add_cap_read(d.rs1_addr, reg_lo32(d.rs1_rdata_lo), d.rs1_rdata_hi);
  if (data_accessed & RS2) add_reg_read(d.rs2_addr, reg_lo32(d.rs2_rdata_lo));
  if (data_accessed & CS2) add_cap_read(d.rs2_addr, reg_lo32(d.rs2_rdata_lo), d.rs2_rdata_hi);
  if (data_accessed & RS3) add_reg_read(d.rs3_addr, reg_lo32(d.rs3_rdata_lo));
  if (data_accessed & RD)  add_reg_write(d.rd_addr, reg_lo32(d.rd_wdata_lo));
  if (data_accessed & CD)  add_cap_write(d.rd_addr, reg_lo32(d.rd_wdata_lo), d.rd_wdata_hi);

  if (data_accessed & MEM) {
    oss << " PA:0x" << std::setw(8) << std::setfill('0') << d.mem_addr;
    if (d.mem_wmask == 0x1) {
      oss << " store:0x??????" << std::setw(2) << std::setfill('0') << (d.mem_wdata_lo & 0xffu);
    } else if (d.mem_wmask == 0x3) {
      oss << " store:0x????" << std::setw(4) << std::setfill('0') << (d.mem_wdata_lo & 0xffffu);
    } else if (d.mem_wmask != 0) {
      oss << " store:0x" << std::setw(8) << std::setfill('0') << reg_lo32(d.mem_wdata_lo);
    }
    if (d.mem_rmask != 0) {
      oss << " load:0x" << std::setw(8) << std::setfill('0') << reg_lo32(d.mem_rdata_lo);
    }
  }

  if (data_accessed & MEMC) {
    oss << " PA:0x" << std::setw(8) << std::setfill('0') << d.mem_addr;
    if (d.mem_wmask != 0) {
      oss << " store:0x" << std::setw(8) << std::setfill('0') << reg_lo32(d.mem_wdata_lo)
          << "+0x" << std::setw(9) << std::setfill('0') << d.mem_wdata_hi;
    } else {
      oss << " load:0x" << std::setw(8) << std::setfill('0') << reg_lo32(d.mem_rdata_lo)
          << "+0x" << std::setw(9) << std::setfill('0') << d.mem_rdata_hi;
      //printf("PA = %x, mem_rdata_hi = %x\n", d.mem_addr, d.mem_rdata_hi);
    }
  }

  return oss.str();
}

static std::string finish(const std::string& s, const RvfiData& d, uint16_t access) {
  return build_disp_str(s, d, access);
}

static std::string decode_mnemonic(const char* mnemonic, const RvfiData& d) {
  return finish(mnemonic, d, 0);
}

static std::string decode_r_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,x%u,x%u", m, d.rd_addr, d.rs1_addr, d.rs2_addr), d, RS1|RS2|RD);
}
static std::string decode_r1_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,x%u", m, d.rd_addr, d.rs1_addr), d, RS1|RD);
}
static std::string decode_r_cmixcmov_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,x%u,x%u,x%u", m, d.rd_addr, d.rs2_addr, d.rs1_addr, d.rs3_addr), d, RS1|RS2|RS3|RD);
}
static std::string decode_r_funnelshift_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,x%u,x%u,x%u", m, d.rd_addr, d.rs1_addr, d.rs3_addr, d.rs2_addr), d, RS1|RS2|RS3|RD);
}
static std::string decode_i_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,x%u,%d", m, d.rd_addr, d.rs1_addr, sext(bits(d.insn,31,20),12)), d, RS1|RD);
}
static std::string decode_i_shift_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,x%u,0x%x", m, d.rd_addr, d.rs1_addr, bits(d.insn,24,20)), d, RS1|RD);
}
static std::string decode_i_funnelshift_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,x%u,x%u,0x%x", m, d.rd_addr, d.rs1_addr, d.rs3_addr, bits(d.insn,25,20)), d, RS1|RS3|RD);
}
static std::string decode_i_jalr_insn(const char* m, const RvfiData& d) {
  int imm = sext(bits(d.insn,31,20),12);
  if (d.cheri_pmode) return finish(fmt("CH.c%s\tc%u,%d(c%u)", m, d.rd_addr, imm, d.rs1_addr), d, CS1|CD);
  return finish(fmt("%s\tx%u,%d(x%u)", m, d.rd_addr, imm, d.rs1_addr), d, RS1|RD);
}
static std::string decode_u_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,0x%x", m, d.rd_addr, bits(d.insn,31,12)), d, RD);
}
static std::string decode_j_insn(const char* m, const RvfiData& d) {
  if (d.cheri_pmode) return finish(fmt("%s\tc%u,%x", "CH.cjal", d.rd_addr, d.pc_wdata), d, CD);
  return finish(fmt("%s\tx%u,%x", m, d.rd_addr, d.pc_wdata), d, RD);
}
static std::string decode_b_insn(const char* m, const RvfiData& d) {
  uint32_t imm = (bits(d.insn,31,31) << 12) | (bits(d.insn,7,7) << 11) |
                 (bits(d.insn,30,25) << 5) | (bits(d.insn,11,8) << 1);
  uint32_t target = d.pc_rdata + static_cast<uint32_t>(sext(imm,13));
  return finish(fmt("%s\tx%u,x%u,%x", m, d.rs1_addr, d.rs2_addr, target), d, RS1|RS2);
}
static std::string decode_csr_insn(const char* m, const RvfiData& d) {
  uint32_t csr = bits(d.insn,31,20);
  std::string csr_name = get_csr_name(csr);
  if (!bits(d.insn,14,14)) {
    return finish(fmt("%s\tx%u,%s,x%u", m, d.rd_addr, csr_name.c_str(), d.rs1_addr), d, RD|RS1);
  }
  return finish(fmt("%s\tx%u,%s,%u", m, d.rd_addr, csr_name.c_str(), bits(d.insn,19,15)), d, RD);
}
static std::string decode_cr_insn(const char* m, const RvfiData& d) {
  if (d.rs2_addr == 0) {
    if (bits(d.insn,12,12) && d.cheri_pmode) return finish(fmt("%s\tc%u", "c.CH.cjalr", d.rs1_addr), d, CS1|CD);
    if (bits(d.insn,12,12)) return finish(fmt("%s\tx%u", m, d.rs1_addr), d, RS1|RD);
    if (d.cheri_pmode) return finish(fmt("%s\tc%u", "c.CH.cjr", d.rs1_addr), d, CS1);
    return finish(fmt("%s\tx%u", m, d.rs1_addr), d, RS1);
  }
  return finish(fmt("%s\tx%u,x%u", m, d.rd_addr, d.rs2_addr), d, RS1|RS2|RD);
}
static std::string decode_ci_cli_insn(const char* m, const RvfiData& d) {
  uint32_t imm = (bits(d.insn,12,12)<<5) | bits(d.insn,6,2);
  return finish(fmt("%s\tx%u,%d", m, d.rd_addr, sext(imm,6)), d, RD);
}
static std::string decode_ci_caddi_insn(const char* m, const RvfiData& d) {
  uint32_t imm = (bits(d.insn,12,12)<<5) | bits(d.insn,6,2);
  return finish(fmt("%s\tx%u,%d", m, d.rd_addr, sext(imm,6)), d, RS1|RD);
}
static std::string decode_ci_caddi16sp_insn(const char* m, const RvfiData& d) {
  uint32_t nzimm = (bits(d.insn,12,12)<<9) | (bits(d.insn,4,3)<<7) |
                   (bits(d.insn,5,5)<<6) | (bits(d.insn,2,2)<<5) |
                   (bits(d.insn,6,6)<<4);
  if (d.cheri_pmode) return finish(fmt("%s\tc%u,%d", "c.CH.cinc16csp", d.rd_addr, sext(nzimm,10)), d, CS1|CD);
  return finish(fmt("%s\tx%u,%d", m, d.rd_addr, sext(nzimm,10)), d, RS1|RD);
}
static std::string decode_ci_clui_insn(const char* m, const RvfiData& d) {
  uint32_t nzimm = (bits(d.insn,12,12)<<5) | bits(d.insn,6,2);
  return finish(fmt("%s\tx%u,0x%x", m, d.rd_addr, static_cast<uint32_t>(sext(nzimm,6)) & ((1u<<20)-1)), d, RD);
}
static std::string decode_ci_cslli_insn(const char* m, const RvfiData& d) {
  uint32_t shamt = (bits(d.insn,12,12)<<5) | bits(d.insn,6,2);
  return finish(fmt("%s\tx%u,0x%x", m, d.rd_addr, shamt), d, RS1|RD);
}
static std::string decode_ciw_insn(const char* m, const RvfiData& d) {
  uint32_t nzuimm = (bits(d.insn,10,7)<<6) | (bits(d.insn,12,11)<<4) |
                    (bits(d.insn,5,5)<<3) | (bits(d.insn,6,6)<<2);
  if (d.cheri_pmode) return finish(fmt("%s\tc%u,csp,%u", m, d.rd_addr, nzuimm), d, CD|CS1);
  return finish(fmt("%s\tx%u,x2,%u", m, d.rd_addr, nzuimm), d, RD);
}
static std::string decode_cb_sr_insn(const char* m, const RvfiData& d) {
  uint32_t shamt = (bits(d.insn,12,12)<<5) | bits(d.insn,6,2);
  return finish(fmt("%s\tx%u,0x%x", m, d.rs1_addr, shamt), d, RS1|RD);
}
static std::string decode_cb_insn(const char* m, const RvfiData& d) {
  if (bits(d.insn,15,13) == 0b110 || bits(d.insn,15,13) == 0b111) {
    uint32_t imm8 = (bits(d.insn,12,12)<<7) | (bits(d.insn,6,5)<<5) |
                    (bits(d.insn,2,2)<<4) | (bits(d.insn,11,10)<<2) |
                    bits(d.insn,4,3);
    uint32_t target = d.pc_rdata + static_cast<uint32_t>(sext((imm8<<1),9));
    return finish(fmt("%s\tx%u,%x", m, d.rs1_addr, target), d, RS1);
  }
  if (bits(d.insn,15,13) == 0b100) {
    uint32_t imm = (bits(d.insn,12,12)<<5) | bits(d.insn,6,2);
    return finish(fmt("%s\tx%u,%d", m, d.rd_addr, sext(imm,6)), d, RS1|RD);
  }
  uint32_t imm = (bits(d.insn,12,12)<<7) | (bits(d.insn,6,2)<<2);
  return finish(fmt("%s\tx%u,0x%x", m, d.rs1_addr, imm), d, RS1);
}
static std::string decode_cs_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,x%u", m, d.rd_addr, d.rs2_addr), d, RS1|RS2|RD);
}
static std::string decode_cj_insn(const char* m, const RvfiData& d) {
  if (bits(d.insn,15,13) == 0b001) {
    if (d.cheri_pmode) return finish(fmt("%s\t%x", "c.CH.cjal", d.pc_wdata), d, CD);
    return finish(fmt("%s\t%x", m, d.pc_wdata), d, RD);
  }
  if (d.cheri_pmode) return finish(fmt("%s\t%x", "c.CH.cj", d.pc_wdata), d, 0);
  return finish(fmt("%s\t%x", m, d.pc_wdata), d, 0);
}
static std::string decode_compressed_load_insn(const char* m, const RvfiData& d) {
  uint32_t imm;
  if (bits(d.insn,15,13) == 0b011 && bits(d.insn,1,0) == 0b00) {
    imm = (bits(d.insn,6,5)<<6) | (bits(d.insn,12,10)<<3);
    return finish(fmt("%s\tc%u,%u(c%u)", m, d.rd_addr, imm, d.rs1_addr), d, CS1|CD|MEMC);
  }
  if (bits(d.insn,15,13) == 0b011 && bits(d.insn,1,0) == 0b10) {
    imm = (bits(d.insn,4,2)<<6) | (bits(d.insn,12,12)<<5) | (bits(d.insn,6,5)<<3);
    return finish(fmt("%s\tc%u,%u(c%u)", m, d.rd_addr, imm, d.rs1_addr), d, CS1|CD|MEMC);
  }
  if (bits(d.insn,1,0) == 0b00)
    imm = (bits(d.insn,5,5)<<6) | (bits(d.insn,12,10)<<3) | (bits(d.insn,6,6)<<2);
  else
    imm = (bits(d.insn,3,2)<<6) | (bits(d.insn,12,12)<<5) | (bits(d.insn,6,4)<<2);
  if (d.cheri_pmode) return finish(fmt("%s\tx%u,%u(c%u)", m, d.rd_addr, imm, d.rs1_addr), d, CS1|RD|MEM);
  return finish(fmt("%s\tx%u,%u(x%u)", m, d.rd_addr, imm, d.rs1_addr), d, RS1|RD|MEM);
}
static std::string decode_compressed_store_insn(const char* m, const RvfiData& d) {
  uint32_t imm;
  if (bits(d.insn,15,13) == 0b111 && bits(d.insn,1,0) == 0b00) {
    imm = (bits(d.insn,6,5)<<6) | (bits(d.insn,12,10)<<3);
    return finish(fmt("%s\tc%u,%u(c%u)", m, d.rs2_addr, imm, d.rs1_addr), d, CS1|CS2|MEMC);
  }
  if (bits(d.insn,15,13) == 0b111 && bits(d.insn,1,0) == 0b10) {
    imm = (bits(d.insn,9,7)<<6) | (bits(d.insn,12,10)<<3);
    return finish(fmt("%s\tc%u,%u(c%u)", m, d.rs2_addr, imm, d.rs1_addr), d, CS1|CS2|MEMC);
  }
  if (bits(d.insn,1,0) == 0b00)
    imm = (bits(d.insn,5,5)<<6) | (bits(d.insn,12,10)<<3) | (bits(d.insn,6,6)<<2);
  else
    imm = (bits(d.insn,8,7)<<6) | (bits(d.insn,12,9)<<2);
  if (d.cheri_pmode) return finish(fmt("%s\tx%u,%u(c%u)", m, d.rs2_addr, imm, d.rs1_addr), d, CS1|RS2|MEM);
  return finish(fmt("%s\tx%u,%u(x%u)", m, d.rs2_addr, imm, d.rs1_addr), d, RS1|RS2|MEM);
}
static std::string decode_load_insn(const RvfiData& d) {
  const char* m = "INVALID";
  bool is_cap = false;
  uint32_t size = bits(d.insn,14,12);
  if (size == 0) m = d.cheri_pmode ? "clb" : "lb";
  else if (size == 1) m = d.cheri_pmode ? "clh" : "lh";
  else if (size == 2) m = d.cheri_pmode ? "clw" : "lw";
  else if (size == 4) m = d.cheri_pmode ? "clbu" : "lbu";
  else if (size == 5) m = d.cheri_pmode ? "clhu" : "lhu";
  else if (size == 3) { m = "CH.clc"; is_cap = true; }
  else return decode_mnemonic("INVALID", d);
  int imm = sext(bits(d.insn,31,20),12);
  if (is_cap) return finish(fmt("%s\tc%u,%d(c%u)", m, d.rd_addr, imm, d.rs1_addr), d, CD|CS1|MEMC);
  if (d.cheri_pmode) return finish(fmt("%s\tx%u,%d(c%u)", m, d.rd_addr, imm, d.rs1_addr), d, RD|CS1|MEM);
  return finish(fmt("%s\tx%u,%d(x%u)", m, d.rd_addr, imm, d.rs1_addr), d, RD|RS1|MEM);
}
static std::string decode_store_insn(const RvfiData& d) {
  const char* m = "INVALID";
  bool is_cap = false;
  switch (bits(d.insn,13,12)) {
    case 0: m = d.cheri_pmode ? "csb" : "sb"; break;
    case 1: m = d.cheri_pmode ? "csh" : "sh"; break;
    case 2: m = d.cheri_pmode ? "csw" : "sw"; break;
    case 3: m = "CH.csc"; is_cap = true; break;
  }
  uint32_t imm12 = (bits(d.insn,31,25)<<5) | bits(d.insn,11,7);
  int imm = sext(imm12,12);
  if (bits(d.insn,14,14)) return decode_mnemonic("INVALID", d);
  if (is_cap) return finish(fmt("%s\tc%u,%d(c%u)", m, d.rs2_addr, imm, d.rs1_addr), d, CS1|CS2|MEMC);
  if (d.cheri_pmode) return finish(fmt("%s\tx%u,%d(c%u)", m, d.rs2_addr, imm, d.rs1_addr), d, CS1|RS2|MEM);
  return finish(fmt("%s\tx%u,%d(x%u)", m, d.rs2_addr, imm, d.rs1_addr), d, RS1|RS2|MEM);
}
static std::string get_fence_description(uint32_t b) {
  std::string s;
  if (b & 8) s += "i";
  if (b & 4) s += "o";
  if (b & 2) s += "r";
  if (b & 1) s += "w";
  return s;
}
static std::string decode_fence(const RvfiData& d) {
  return finish(fmt("fence\t%s,%s", get_fence_description(bits(d.insn,27,24)).c_str(),
                    get_fence_description(bits(d.insn,23,20)).c_str()), d, 0);
}
static std::string decode_cheri_rd_rs1_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,x%u", m, d.rd_addr, d.rs1_addr), d, RS1|RD);
}
static std::string decode_cheri_rd_cs1_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,c%u", m, d.rd_addr, d.rs1_addr), d, CS1|RD);
}
static std::string decode_cheri_cd_cs1_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tc%u,c%u", m, d.rd_addr, d.rs1_addr), d, CS1|CD);
}
static std::string decode_cheri_rd_cs1_cs2_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,c%u,c%u", m, d.rd_addr, d.rs1_addr, d.rs2_addr), d, CS2|CS1|RD);
}
static std::string decode_cheri_cd_cs1_cs2_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tc%u,c%u,c%u", m, d.rd_addr, d.rs1_addr, d.rs2_addr), d, CS2|CS1|CD);
}
static std::string decode_cheri_cd_cs1_rs2_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tc%u,c%u,x%u", m, d.rd_addr, d.rs1_addr, d.rs2_addr), d, RS2|CS1|CD);
}
static std::string decode_cheri_cd_cs1_imm_insn(const char* m, const RvfiData& d) {
  uint32_t imm = bits(d.insn,31,20);
  uint32_t imm31 = bits(d.insn,31,31);

  //  imm = {{3{rvfi_data.insn[31]}}, rvfi_data.insn[30:20]};  // imm not extended
  imm |= ((imm31 <<12) | (imm31 << 13));

  if (bits(d.insn,14,12) == 1)  //cincaddrimm
    return finish(fmt("%s\tc%u,c%u,%d", m, d.rd_addr, d.rs1_addr, sext(imm,14)), d, CS1|CD);
  // csetboundsimm
  //printf("csetboundsimm (%x): %d\n", d.insn, imm);
  return finish(fmt("%s\tc%u,c%u,%d", m, d.rd_addr, d.rs1_addr, imm), d, CS1|CD);
}
static std::string decode_cheri_auipcc_insn(const RvfiData& d) {
  uint32_t imm = bits(d.insn,31,12);
  if (d.cheri_pmode) return finish(fmt("%s\tc%u,0x%x", "CH.auipcc", d.rd_addr, imm), d, CD);
  return finish(fmt("%s\tx%u,0x%x", "auipc", d.rd_addr, imm), d, CD);
}
static std::string decode_cheri_auicgp_insn(const RvfiData& d) {
  uint32_t imm = bits(d.insn,31,12);
  return finish(fmt("%s\tc%u,0x%x", "CH.auicgp", d.rd_addr, imm), d, CD|CS1);
}
static std::string decode_cheri_cs1_cs2_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tc%u,c%u", m, d.rs1_addr, d.rs2_addr), d, CS2|CS1);
}
static std::string decode_cheri_scrrw_insn(const RvfiData& d) {
  std::string scr = get_scr_name(bits(d.insn,24,20));
  if (d.rd_addr == 0) return finish(fmt("%s\t%s,c%u", "CH.cspecialw", scr.c_str(), d.rs1_addr), d, CS1|CD);
  if (d.rs1_addr == 0) return finish(fmt("%s\tc%u,%s", "CH.cspecialr", d.rd_addr, scr.c_str()), d, CS1|CD);
  return finish(fmt("%s\tc%u,%s,c%u", "CH.cspecialrw", d.rd_addr, scr.c_str(), d.rs1_addr), d, CS1|CD);
}
static std::string decode_amo_insn(const char* m, const RvfiData& d) {
  return finish(fmt("%s\tx%u,x%u,x%u", m, d.rd_addr, d.rs1_addr, d.rs2_addr), d, RS1|RS2|RD|MEM);
}

static std::string decode_rvfi_instr_cpp(const RvfiData& d) {
  if (d.intr) return "==>";
  // printf("rs1_rdata_lo = %x, rx1_rdata_hi = %x\n", d.rs1_rdata_lo, d.rs1_rdata_hi);

  if ((d.insn & 0x3u) != 0x3u) {
    if (bits(d.insn,15,13) == bits(INSN_CMV.value,15,13) && bits(d.insn,1,0) == 0b10) {
      if (bits(d.insn,12,12) == bits(INSN_CADD.value,12,12)) {
        if (bits(d.insn,11,2) == bits(INSN_CEBREAK.value,11,2)) return decode_mnemonic("c.ebreak", d);
        if (bits(d.insn,6,2) == bits(INSN_CJALR.value,6,2)) return decode_cr_insn("c.jalr", d);
        return decode_cr_insn("c.add", d);
      } else {
        if (bits(d.insn,6,2) == bits(INSN_CJR.value,6,2)) return decode_cr_insn("c.jr", d);
        return decode_cr_insn("c.mv", d);
      }
    }

    if (match(d.insn, INSN_CADDI4SPN)) {
      if (bits(d.insn,12,2) == 0) return decode_mnemonic("c.unimp", d);
      return decode_ciw_insn("c.addi4spn", d);
    }
    if (match(d.insn, INSN_CLUI)) {
      if (bits(d.insn,11,7) == 2) return decode_ci_caddi16sp_insn("c.addi16sp", d);
      return decode_ci_clui_insn("c.lui", d);
    }
    if (match(d.insn, INSN_CLW)) return decode_compressed_load_insn("c.lw", d);
    if (match(d.insn, INSN_CSW)) return decode_compressed_store_insn("c.sw", d);
    if (match(d.insn, INSN_CCLC)) return decode_compressed_load_insn("c.CH.clc", d);
    if (match(d.insn, INSN_CCSC)) return decode_compressed_store_insn("c.CH.csc", d);
    if (match(d.insn, INSN_CADDI)) return decode_ci_caddi_insn("c.addi", d);
    if (match(d.insn, INSN_CJAL)) return decode_cj_insn("c.jal", d);
    if (match(d.insn, INSN_CJ)) return decode_cj_insn("c.j", d);
    if (match(d.insn, INSN_CLI)) return decode_ci_cli_insn("c.li", d);
    if (match(d.insn, INSN_CSRLI)) return decode_cb_sr_insn("c.srli", d);
    if (match(d.insn, INSN_CSRAI)) return decode_cb_sr_insn("c.srai", d);
    if (match(d.insn, INSN_CANDI)) return decode_cb_insn("c.andi", d);
    if (match(d.insn, INSN_CSUB)) return decode_cs_insn("c.sub", d);
    if (match(d.insn, INSN_CXOR)) return decode_cs_insn("c.xor", d);
    if (match(d.insn, INSN_COR)) return decode_cs_insn("c.or", d);
    if (match(d.insn, INSN_CAND)) return decode_cs_insn("c.and", d);
    if (match(d.insn, INSN_CBEQZ)) return decode_cb_insn("c.beqz", d);
    if (match(d.insn, INSN_CBNEZ)) return decode_cb_insn("c.bnez", d);
    if (match(d.insn, INSN_CSLLI)) return decode_ci_cslli_insn("c.slli", d);
    if (match(d.insn, INSN_CLWSP)) return decode_compressed_load_insn("c.lwsp", d);
    if (match(d.insn, INSN_SWSP)) return decode_compressed_store_insn("c.swsp", d);
    if (match(d.insn, INSN_CCLCSP)) return decode_compressed_load_insn("c.CH.clcsp", d);
    if (match(d.insn, INSN_CCSCSP)) return decode_compressed_store_insn("c.CH.cscsp", d);
    return decode_mnemonic("INVALID", d);
  }

    if (match(d.insn, INSN_LUI)) return decode_u_insn("lui", d);
    if (match(d.insn, INSN_JAL)) return decode_j_insn("jal", d);
    if (match(d.insn, INSN_JALR)) return decode_i_jalr_insn("jalr", d);
    if (match(d.insn, INSN_BEQ)) return decode_b_insn("beq", d);
    if (match(d.insn, INSN_BNE)) return decode_b_insn("bne", d);
    if (match(d.insn, INSN_BLT)) return decode_b_insn("blt", d);
    if (match(d.insn, INSN_BGE)) return decode_b_insn("bge", d);
    if (match(d.insn, INSN_BLTU)) return decode_b_insn("bltu", d);
    if (match(d.insn, INSN_BGEU)) return decode_b_insn("bgeu", d);
    if (match(d.insn, INSN_ADDI)) return decode_i_insn("addi", d);
    if (match(d.insn, INSN_SLTI)) return decode_i_insn("slti", d);
    if (match(d.insn, INSN_SLTIU)) return decode_i_insn("sltiu", d);
    if (match(d.insn, INSN_XORI)) return decode_i_insn("xori", d);
    if (match(d.insn, INSN_ORI)) return decode_i_insn("ori", d);
    if (match(d.insn, INSN_ANDI)) return decode_i_insn("andi", d);
    if (match(d.insn, INSN_SLLI)) return decode_i_shift_insn("slli", d);
    if (match(d.insn, INSN_SRLI)) return decode_i_shift_insn("srli", d);
    if (match(d.insn, INSN_SRAI)) return decode_i_shift_insn("srai", d);
    if (match(d.insn, INSN_ADD)) return decode_r_insn("add", d);
    if (match(d.insn, INSN_SUB)) return decode_r_insn("sub", d);
    if (match(d.insn, INSN_SLL)) return decode_r_insn("sll", d);
    if (match(d.insn, INSN_SLT)) return decode_r_insn("slt", d);
    if (match(d.insn, INSN_SLTU)) return decode_r_insn("sltu", d);
    if (match(d.insn, INSN_XOR)) return decode_r_insn("xor", d);
    if (match(d.insn, INSN_SRL)) return decode_r_insn("srl", d);
    if (match(d.insn, INSN_SRA)) return decode_r_insn("sra", d);
    if (match(d.insn, INSN_OR)) return decode_r_insn("or", d);
    if (match(d.insn, INSN_AND)) return decode_r_insn("and", d);
    if (match(d.insn, INSN_CSRRW)) return decode_csr_insn("csrrw", d);
    if (match(d.insn, INSN_CSRRS)) return decode_csr_insn("csrrs", d);
    if (match(d.insn, INSN_CSRRC)) return decode_csr_insn("csrrc", d);
    if (match(d.insn, INSN_CSRRWI)) return decode_csr_insn("csrrwi", d);
    if (match(d.insn, INSN_CSRRSI)) return decode_csr_insn("csrrsi", d);
    if (match(d.insn, INSN_CSRRCI)) return decode_csr_insn("csrrci", d);
    if (match(d.insn, INSN_PMUL)) return decode_r_insn("mul", d);
    if (match(d.insn, INSN_PMUH)) return decode_r_insn("mulh", d);
    if (match(d.insn, INSN_PMULHSU)) return decode_r_insn("mulhsu", d);
    if (match(d.insn, INSN_PMULHU)) return decode_r_insn("mulhu", d);
    if (match(d.insn, INSN_DIV)) return decode_r_insn("div", d);
    if (match(d.insn, INSN_DIVU)) return decode_r_insn("divu", d);
    if (match(d.insn, INSN_REM)) return decode_r_insn("rem", d);
    if (match(d.insn, INSN_REMU)) return decode_r_insn("remu", d);
    if (match(d.insn, INSN_SH1ADD)) return decode_r_insn("sh1add", d);
    if (match(d.insn, INSN_SH2ADD)) return decode_r_insn("sh2add", d);
    if (match(d.insn, INSN_SH3ADD)) return decode_r_insn("sh3add", d);
    if (match(d.insn, INSN_RORI)) return decode_i_shift_insn("rori", d);
    if (match(d.insn, INSN_ROL)) return decode_r_insn("rol", d);
    if (match(d.insn, INSN_ROR)) return decode_r_insn("ror", d);
    if (match(d.insn, INSN_MIN)) return decode_r_insn("min", d);
    if (match(d.insn, INSN_MAX)) return decode_r_insn("max", d);
    if (match(d.insn, INSN_MINU)) return decode_r_insn("minu", d);
    if (match(d.insn, INSN_MAXU)) return decode_r_insn("maxu", d);
    if (match(d.insn, INSN_XNOR)) return decode_r_insn("xnor", d);
    if (match(d.insn, INSN_ORN)) return decode_r_insn("orn", d);
    if (match(d.insn, INSN_ANDN)) return decode_r_insn("andn", d);
    if (match(d.insn, INSN_PACK)) return decode_r_insn("pack", d);
    if (match(d.insn, INSN_PACKH)) return decode_r_insn("packh", d);
    if (match(d.insn, INSN_PACKU)) return decode_r_insn("packu", d);
    if (match(d.insn, INSN_CLZ)) return decode_r1_insn("clz", d);
    if (match(d.insn, INSN_CTZ)) return decode_r1_insn("ctz", d);
    if (match(d.insn, INSN_CPOP)) return decode_r1_insn("cpop", d);
    if (match(d.insn, INSN_SEXTB)) return decode_r1_insn("sext.b", d);
    if (match(d.insn, INSN_SEXTH)) return decode_r1_insn("sext.h", d);
    if (match(d.insn, INSN_BCLRI)) return decode_i_insn("bclri", d);
    if (match(d.insn, INSN_BSETI)) return decode_i_insn("bseti", d);
    if (match(d.insn, INSN_BINVI)) return decode_i_insn("binvi", d);
    if (match(d.insn, INSN_BEXTI)) return decode_i_insn("bexti", d);
    if (match(d.insn, INSN_BCLR)) return decode_r_insn("bclr", d);
    if (match(d.insn, INSN_BSET)) return decode_r_insn("bset", d);
    if (match(d.insn, INSN_BINV)) return decode_r_insn("binv", d);
    if (match(d.insn, INSN_BEXT)) return decode_r_insn("bext", d);
    if (match(d.insn, INSN_BDECOMPRESS)) return decode_r_insn("bdecompress", d);
    if (match(d.insn, INSN_BCOMPRESS)) return decode_r_insn("bcompress", d);
    if (match(d.insn, INSN_GREV)) return decode_r_insn("grev", d);
    if (match(d.insn, INSN_REV_P)) return decode_r1_insn("rev.p", d);
    if (match(d.insn, INSN_REV2_N)) return decode_r1_insn("rev2.n", d);
    if (match(d.insn, INSN_REV_N)) return decode_r1_insn("rev.n", d);
    if (match(d.insn, INSN_REV4_B)) return decode_r1_insn("rev4.b", d);
    if (match(d.insn, INSN_REV2_B)) return decode_r1_insn("rev2.b", d);
    if (match(d.insn, INSN_REV_B)) return decode_r1_insn("rev.b", d);
    if (match(d.insn, INSN_REV8_H)) return decode_r1_insn("rev8.h", d);
    if (match(d.insn, INSN_REV4_H)) return decode_r1_insn("rev4.h", d);
    if (match(d.insn, INSN_REV2_H)) return decode_r1_insn("rev2.h", d);
    if (match(d.insn, INSN_REV_H)) return decode_r1_insn("rev.h", d);
    if (match(d.insn, INSN_REV16)) return decode_r1_insn("rev16", d);
    if (match(d.insn, INSN_REV8)) return decode_r1_insn("rev8", d);
    if (match(d.insn, INSN_REV4)) return decode_r1_insn("rev4", d);
    if (match(d.insn, INSN_REV2)) return decode_r1_insn("rev2", d);
    if (match(d.insn, INSN_REV)) return decode_r1_insn("rev", d);
    if (match(d.insn, INSN_GORC)) return decode_r_insn("gorc", d);
    if (match(d.insn, INSN_ORC_P)) return decode_r1_insn("orc.p", d);
    if (match(d.insn, INSN_ORC2_N)) return decode_r1_insn("orc2.n", d);
    if (match(d.insn, INSN_ORC_N)) return decode_r1_insn("orc.n", d);
    if (match(d.insn, INSN_ORC4_B)) return decode_r1_insn("orc4.b", d);
    if (match(d.insn, INSN_ORC2_B)) return decode_r1_insn("orc2.b", d);
    if (match(d.insn, INSN_ORC_B)) return decode_r1_insn("orc.b", d);
    if (match(d.insn, INSN_ORC8_H)) return decode_r1_insn("orc8.h", d);
    if (match(d.insn, INSN_ORC4_H)) return decode_r1_insn("orc4.h", d);
    if (match(d.insn, INSN_ORC2_H)) return decode_r1_insn("orc2.h", d);
    if (match(d.insn, INSN_ORC_H)) return decode_r1_insn("orc.h", d);
    if (match(d.insn, INSN_ORC16)) return decode_r1_insn("orc16", d);
    if (match(d.insn, INSN_ORC8)) return decode_r1_insn("orc8", d);
    if (match(d.insn, INSN_ORC4)) return decode_r1_insn("orc4", d);
    if (match(d.insn, INSN_ORC2)) return decode_r1_insn("orc2", d);
    if (match(d.insn, INSN_ORC)) return decode_r1_insn("orc", d);
    if (match(d.insn, INSN_SHFL)) return decode_r_insn("shfl", d);
    if (match(d.insn, INSN_ZIP_N)) return decode_r1_insn("zip.n", d);
    if (match(d.insn, INSN_ZIP2_B)) return decode_r1_insn("zip2.b", d);
    if (match(d.insn, INSN_ZIP_B)) return decode_r1_insn("zip.b", d);
    if (match(d.insn, INSN_ZIP4_H)) return decode_r1_insn("zip4.h", d);
    if (match(d.insn, INSN_ZIP2_H)) return decode_r1_insn("zip2.h", d);
    if (match(d.insn, INSN_ZIP_H)) return decode_r1_insn("zip.h", d);
    if (match(d.insn, INSN_ZIP8)) return decode_r1_insn("zip8", d);
    if (match(d.insn, INSN_ZIP4)) return decode_r1_insn("zip4", d);
    if (match(d.insn, INSN_ZIP2)) return decode_r1_insn("zip2", d);
    if (match(d.insn, INSN_ZIP)) return decode_r1_insn("zip", d);
    if (match(d.insn, INSN_UNSHFL)) return decode_r_insn("unshfl", d);
    if (match(d.insn, INSN_UNZIP_N)) return decode_r1_insn("unzip.n", d);
    if (match(d.insn, INSN_UNZIP2_B)) return decode_r1_insn("unzip2.b", d);
    if (match(d.insn, INSN_UNZIP_B)) return decode_r1_insn("unzip.b", d);
    if (match(d.insn, INSN_UNZIP4_H)) return decode_r1_insn("unzip4.h", d);
    if (match(d.insn, INSN_UNZIP2_H)) return decode_r1_insn("unzip2.h", d);
    if (match(d.insn, INSN_UNZIP_H)) return decode_r1_insn("unzip.h", d);
    if (match(d.insn, INSN_UNZIP8)) return decode_r1_insn("unzip8", d);
    if (match(d.insn, INSN_UNZIP4)) return decode_r1_insn("unzip4", d);
    if (match(d.insn, INSN_UNZIP2)) return decode_r1_insn("unzip2", d);
    if (match(d.insn, INSN_UNZIP)) return decode_r1_insn("unzip", d);
    if (match(d.insn, INSN_XPERM_N)) return decode_r_insn("xperm_n", d);
    if (match(d.insn, INSN_XPERM_B)) return decode_r_insn("xperm_b", d);
    if (match(d.insn, INSN_XPERM_H)) return decode_r_insn("xperm_h", d);
    if (match(d.insn, INSN_SLO)) return decode_r_insn("slo", d);
    if (match(d.insn, INSN_SRO)) return decode_r_insn("sro", d);
    if (match(d.insn, INSN_SLOI)) return decode_i_shift_insn("sloi", d);
    if (match(d.insn, INSN_SROI)) return decode_i_shift_insn("sroi", d);
    if (match(d.insn, INSN_CMIX)) return decode_r_cmixcmov_insn("cmix", d);
    if (match(d.insn, INSN_CMOV)) return decode_r_cmixcmov_insn("cmov", d);
    if (match(d.insn, INSN_FSR)) return decode_r_funnelshift_insn("fsr", d);
    if (match(d.insn, INSN_FSL)) return decode_r_funnelshift_insn("fsl", d);
    if (match(d.insn, INSN_FSRI)) return decode_i_funnelshift_insn("fsri", d);
    if (match(d.insn, INSN_BFP)) return decode_r_insn("bfp", d);
    if (match(d.insn, INSN_CLMUL)) return decode_r_insn("clmul", d);
    if (match(d.insn, INSN_CLMULR)) return decode_r_insn("clmulr", d);
    if (match(d.insn, INSN_CLMULH)) return decode_r_insn("clmulh", d);
    if (match(d.insn, INSN_CRC32_B)) return decode_r1_insn("crc32.b", d);
    if (match(d.insn, INSN_CRC32_H)) return decode_r1_insn("crc32.h", d);
    if (match(d.insn, INSN_CRC32_W)) return decode_r1_insn("crc32.w", d);
    if (match(d.insn, INSN_CRC32C_B)) return decode_r1_insn("crc32c.b", d);
    if (match(d.insn, INSN_CRC32C_H)) return decode_r1_insn("crc32c.h", d);
    if (match(d.insn, INSN_CRC32C_W)) return decode_r1_insn("crc32c.w", d);
    if (match(d.insn, INSN_CHGETPERM)) return decode_cheri_rd_cs1_insn("CH.cgetperm", d);
    if (match(d.insn, INSN_CHGETTYPE)) return decode_cheri_rd_cs1_insn("CH.cgettype", d);
    if (match(d.insn, INSN_CHGETBASE)) return decode_cheri_rd_cs1_insn("CH.cgetbase", d);
    if (match(d.insn, INSN_CHGETTOP)) return decode_cheri_rd_cs1_insn("CH.cgettop", d);
    if (match(d.insn, INSN_CHGETLEN)) return decode_cheri_rd_cs1_insn("CH.cgetlen", d);
    if (match(d.insn, INSN_CHGETTAG)) return decode_cheri_rd_cs1_insn("CH.cgettag", d);
    if (match(d.insn, INSN_CHGETSEALED)) return decode_cheri_rd_cs1_insn("CH.cgetseald", d);
    if (match(d.insn, INSN_CHGETADDR)) return decode_cheri_rd_cs1_insn("CH.cgetaddr", d);
    if (match(d.insn, INSN_CHGETHIGH)) return decode_cheri_rd_cs1_insn("CH.cgethigh", d);
    if (match(d.insn, INSN_CHSEAL)) return decode_cheri_cd_cs1_cs2_insn("CH.cseal", d);
    if (match(d.insn, INSN_CHUNSEAL)) return decode_cheri_cd_cs1_cs2_insn("CH.cunseal", d);
    if (match(d.insn, INSN_CHANDPERM)) return decode_cheri_cd_cs1_rs2_insn("CH.candperm", d);
    if (match(d.insn, INSN_CHSETADDR)) return decode_cheri_cd_cs1_rs2_insn("CH.csetaddr", d);
    if (match(d.insn, INSN_CHINCADDR)) return decode_cheri_cd_cs1_rs2_insn("CH.cincaddr", d);
    if (match(d.insn, INSN_CHINCADDRIMM)) return decode_cheri_cd_cs1_imm_insn("CH.cincaddrimm", d);
    if (match(d.insn, INSN_CHSETBOUNDS)) return decode_cheri_cd_cs1_rs2_insn("CH.csetbounds", d);
    if (match(d.insn, INSN_CHSETBOUNDSEX)) return decode_cheri_cd_cs1_rs2_insn("CH.csetboundsexact", d);
    if (match(d.insn, INSN_CHSETBOUNDSRNDN)) return decode_cheri_cd_cs1_rs2_insn("CH.csetboundsrounddown", d);
    if (match(d.insn, INSN_CHSETBOUNDSIMM)) return decode_cheri_cd_cs1_imm_insn("CH.csetboundsimm", d);
    if (match(d.insn, INSN_CHCLEARTAG)) return decode_cheri_cd_cs1_insn("CH.ccleartag", d);
    if (match(d.insn, INSN_CHCRRL)) return decode_cheri_rd_rs1_insn("CH.crrl", d);
    if (match(d.insn, INSN_CHCRAM)) return decode_cheri_rd_rs1_insn("CH.cram", d);
    if (match(d.insn, INSN_CHSUB)) return decode_cheri_rd_cs1_cs2_insn("CH.csub", d);
    if (match(d.insn, INSN_CHMOVE)) return decode_cheri_cd_cs1_insn("CH.cmove", d);
    if (match(d.insn, INSN_CHTESTSUB)) return decode_cheri_rd_cs1_cs2_insn("CH.ctestsubset", d);
    if (match(d.insn, INSN_CHSETEQUAL)) return decode_cheri_rd_cs1_cs2_insn("CH.csetequalexact", d);
    if (match(d.insn, INSN_CHSETHIGH)) return decode_cheri_cd_cs1_rs2_insn("CH.csethigh", d);
    if (match(d.insn, INSN_LR)) return decode_amo_insn("lr.w", d);
    if (match(d.insn, INSN_SC)) return decode_amo_insn("sc.w", d);
    if (match(d.insn, INSN_AMOSWAP)) return decode_amo_insn("amoswap.w", d);
    if (match(d.insn, INSN_AMOADD)) return decode_amo_insn("amoadd.w", d);
    if (match(d.insn, INSN_AMOXOR)) return decode_amo_insn("amoxor.w", d);
    if (match(d.insn, INSN_AMOOR)) return decode_amo_insn("amoor.w", d);
    if (match(d.insn, INSN_AMOMIN)) return decode_amo_insn("amomin.w", d);
    if (match(d.insn, INSN_AMOMAX)) return decode_amo_insn("amomax.w", d);
    if (match(d.insn, INSN_AMOMINU)) return decode_amo_insn("amominu.w", d);
    if (match(d.insn, INSN_AMOMAXU)) return decode_amo_insn("amomaxu.w", d);
    if (match(d.insn, INSN_ECALL)) return decode_mnemonic("ecall", d);
    if (match(d.insn, INSN_EBREAK)) return decode_mnemonic("ebreak", d);
    if (match(d.insn, INSN_MRET)) return decode_mnemonic("mret", d);
    if (match(d.insn, INSN_DRET)) return decode_mnemonic("dret", d);
    if (match(d.insn, INSN_WFI)) return decode_mnemonic("wfi", d);
    if (match(d.insn, INSN_FENCEI)) return decode_mnemonic("fence.i", d);
    if (match(d.insn, INSN_LOAD)) return decode_load_insn(d);
    if (match(d.insn, INSN_STORE)) return decode_store_insn(d);
    if (match(d.insn, INSN_FENCE)) return decode_fence(d);
    if (match(d.insn, INSN_CHCSRRW)) return decode_cheri_scrrw_insn(d);
    if (match(d.insn, INSN_AUIPC)) return decode_cheri_auipcc_insn(d);
    if (match(d.insn, INSN_AUICGP)) return decode_cheri_auicgp_insn(d);
    if (match(d.insn, INSN_GREVI)) return decode_i_insn("grevi", d);
    if (match(d.insn, INSN_GORCI)) return decode_i_insn("gorci", d);
    if (match(d.insn, INSN_SHFLI)) return decode_i_insn("shfli", d);
    if (match(d.insn, INSN_UNSHFLI)) return decode_i_insn("unshfli", d);
  return decode_mnemonic("INVALID", d);
}

} // namespace tracer_dpi

extern "C" const char* decode_rvfi_instr(
    uint32_t insn,
    uint8_t trap,
    uint8_t intr,
    uint8_t rs1_addr,
    uint8_t rs2_addr,
    uint8_t rs3_addr,
    uint32_t rs1_rdata_lo,
    uint32_t rs2_rdata_lo,
    uint32_t rs3_rdata_lo,
    uint64_t rs1_rdata_hi,
    uint64_t rs2_rdata_hi,
    uint64_t rs3_rdata_hi,
    uint8_t rd_addr,
    uint32_t rd_wdata_lo,
    uint64_t rd_wdata_hi,
    uint32_t pc_rdata,
    uint32_t pc_wdata,
    uint32_t mem_addr,
    uint8_t mem_rmask,
    uint8_t mem_wmask,
    uint32_t mem_rdata_lo,
    uint32_t mem_wdata_lo,
    uint64_t mem_rdata_hi,
    uint64_t mem_wdata_hi,
    uint8_t cheri_pmode) {
  static thread_local std::string result;
  tracer_dpi::RvfiData d{};
  d.insn = insn;
  d.trap = trap != 0;
  d.intr = intr != 0;
  d.rs1_addr = rs1_addr;
  d.rs2_addr = rs2_addr;
  d.rs3_addr = rs3_addr;
  d.rs1_rdata_lo = rs1_rdata_lo;
  d.rs2_rdata_lo = rs2_rdata_lo;
  d.rs3_rdata_lo = rs3_rdata_lo;
  d.rs1_rdata_hi = rs1_rdata_hi;
  d.rs2_rdata_hi = rs2_rdata_hi;
  d.rs3_rdata_hi = rs3_rdata_hi;
  d.rd_addr = rd_addr;
  d.rd_wdata_lo = rd_wdata_lo;
  d.rd_wdata_hi = rd_wdata_hi;
  d.pc_rdata = pc_rdata;
  d.pc_wdata = pc_wdata;
  d.mem_addr = mem_addr;
  d.mem_rmask = mem_rmask;
  d.mem_wmask = mem_wmask;
  d.mem_rdata_lo = mem_rdata_lo;
  d.mem_wdata_lo = mem_wdata_lo;
  d.mem_rdata_hi = mem_rdata_hi;
  d.mem_wdata_hi = mem_wdata_hi;
  d.cheri_pmode = cheri_pmode != 0;

  //printf("rs1_rdata_lo = %x, rx1_rdata_hi = %x\n", d.rs1_rdata_lo, d.rs1_rdata_hi);
  result = tracer_dpi::decode_rvfi_instr_cpp(d);
  return result.c_str();
}
